[package]
name = "rulid"
version = "0.1.0"
edition = "2021"
author = "Christian Kemper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
ulid = "1.0.0"
